language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g   #生成
env:
 global:
   - GH_REF: git@gitee.com:didiplus/didiplus.git  #设置GH_REF，注意更改yourname

branches:
  only:
    - blog-source  #只监测source分支，source是我的分支的名称，可根据自己情况设置

after_script:
  - cd ./public
  - git init
  - git config user.name "didiplus"  #修改name
  - git config user.email "972479352@qq.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet https://${GITEE_TOKEN}@${GH_REF} master:master


